name: Build HyperType

# When does this run?
on:
  # Run when you create a new release on GitHub
  release:
    types: [published]

jobs:
  build:
    # Run this job on 3 different OS simultaneously
    runs-on: ${{ matrix.os }}

    # This creates 3 parallel jobs
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          # Windows config
          - os: windows-latest
            output-name: hypertype-windows.exe

          # Linux config
          - os: ubuntu-latest
            output-name: hypertype-linux

          # Mac config
          - os: macos-latest
            output-name: hypertype-mac

    steps:
      # Step 1: Get the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Build the executable
      - name: Build Executable
        run: pyinstaller hypertype.spec

      # Step 5: Rename the output file per OS
      - name: Rename Output
        run: |
          # Windows
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/hypertype.exe dist/${{ matrix.output-name }}
          fi
          # Linux
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            mv dist/hypertype dist/${{ matrix.output-name }}
          fi
          # Mac
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            mv dist/hypertype dist/${{ matrix.output-name }}
          fi

      # Step 6: Upload the binary to the GitHub Release
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.output-name }}
